"""empty message

Revision ID: 2c3376e274f3
Revises: 
Create Date: 2023-10-13 09:50:16.437766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c3376e274f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('_password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('name', name=op.f('uq_users_name'))
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('range_min', sa.Integer(), nullable=False),
    sa.Column('range_max', sa.Integer(), nullable=False),
    sa.Column('secret_number', sa.Integer(), nullable=True),
    sa.Column('is_over', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('range_min <= range_max', name=op.f('ck_games_min_max_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_games_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_games'))
    )
    op.create_table('rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('range_min', sa.Integer(), nullable=False),
    sa.Column('range_max', sa.Integer(), nullable=False),
    sa.Column('guess', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('range_min <= range_max', name=op.f('ck_rounds_min_max_range')),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_rounds_game_id_games')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rounds'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rounds')
    op.drop_table('games')
    op.drop_table('users')
    # ### end Alembic commands ###
