"""change password column on users

Revision ID: 45471ee4f0c3
Revises: c85ef3cf873c
Create Date: 2023-10-10 11:23:07.612964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45471ee4f0c3'
down_revision = 'c85ef3cf873c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password_hash', sa.String(length=255), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('_password_hash')

    # ### end Alembic commands ###
